/*
 * This file is generated by jOOQ.
*/
package com.panshi.webtemplate.model;


import com.panshi.webtemplate.model.tables.Author;
import com.panshi.webtemplate.model.tables.AuthorMappingBook;
import com.panshi.webtemplate.model.tables.Book;
import com.panshi.webtemplate.model.tables.Comments;
import com.panshi.webtemplate.model.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooqtemplate
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooqtemplate.author</code>.
     */
    public static final Author AUTHOR = com.panshi.webtemplate.model.tables.Author.AUTHOR;

    /**
     * The table <code>jooqtemplate.author_mapping_book</code>.
     */
    public static final AuthorMappingBook AUTHOR_MAPPING_BOOK = com.panshi.webtemplate.model.tables.AuthorMappingBook.AUTHOR_MAPPING_BOOK;

    /**
     * book table
     */
    public static final Book BOOK = com.panshi.webtemplate.model.tables.Book.BOOK;

    /**
     * The table <code>jooqtemplate.comments</code>.
     */
    public static final Comments COMMENTS = com.panshi.webtemplate.model.tables.Comments.COMMENTS;

    /**
     * The table <code>jooqtemplate.posts</code>.
     */
    public static final Posts POSTS = com.panshi.webtemplate.model.tables.Posts.POSTS;
}
